### ISSUE TITLE
Rename crate?

### ISSUE THREAD

**Issue by virtualritz** [polymonster/maths-rs#2]
The Rust naming guidelines are [very explicit about crate names ending with `-rs`](https://rust-lang.github.io/api-guidelines/naming.html#:~:text=Crate%20names%20should%20not%20use,remind%20users%20of%20this%20constantly.).

I suggest to rename this crate to `polymath` which both carries [meaning as a term](https://en.wikipedia.org/wiki/Polymath) and nicely combines part of your GH handle, `polymonster`, with the word `math`.

Additionally `polymath` is available on `crates.io`.

**Comment by polymonster** [comment]
In terms of the naming, the GitHub repo was named this way to disambiguate from my C++ [maths](https://github.com/polymonster/maths-rs) lib, but also it basically shares the same feature set... it is the rust equivalent, so in this instance I do not think the -rs is redundant in the GitHub context.

As for the crate itself I would have loved to just use `maths` without the -rs but someone has selfishly taken the package name [maths](https://crates.io/crates/maths) and not done any work with it, which is extremely annoying and the same thing also happened to hotline which is another of my projects. So sadly I just had to stick the -rs on at the last minute. 

At this time I don't think I can really undertake the job of renaming the crate, it is used in a few places and it would require people to be aware that the crate has moved. I am starting a new job this week and I need to focus on that so will be taking a step back from open source stuff for a little while at least.

I suppose the ideal solution would be to contact the owner of maths on crates.io and persuade them to transfer ownership of the maths crate...

I'll keep this open for now and have a think of it, but thanks for bringing it to attention.

**Comment by virtualritz** [comment]
Yes, contacting the owner is the way. I had another crate that was stale transfered to me after asking nicely.
