### ISSUE TITLE
Hash for Vec2i, Vec3i

### ISSUE THREAD

**Issue by markusmoenig** [polymonster/maths-rs#5]
Hi, 

great job with the library.

One small suggestion, as I am doing a lot of work with 2D tiles, I use stuff like ```FxHashMap<(i32, i32), Tile>``` etc a lot where I always need to convert from Vec2i / Vec3i values from / to tuples to make the Hash work. 

Would it be possible to derive from Hash for Vec2i / Vec3i ? Than I could use these directly ... .

Thanks!

**Comment by polymonster** [comment]
Yeah sure, sounds like something worth adding. I can take a look.

**Comment by polymonster** [comment]
I added support for `hash` on an optional feature of the crate, you can enabled the `hash` feature which will work for integer vectors and matrices. The commit is here: https://github.com/polymonster/maths-rs/commit/537c1ddae82385be85c13af2d3ac5f15f5b25465

I also tagged a new release which is `0.2.6` and is available on [crates.io](https://crates.io/crates/maths-rs) now. 

Let me know how you get on, I added a test for it so I think it's working but didn't have a proper use case :)

**Comment by markusmoenig** [comment]
Works great, thanks a lot!
